(function () {
    'use strict';
    // Palettes météociel (couleurs exactes extraites de meteociel.fr).
    var PALETTES = {
        temperature: {
            label: 'Température à 2 m', unit: '°C', decimals: 0, transparent_below: null,
            stops: [
                { value: -24, color: '#400040' },
                { value: -22, color: '#600060' },
                { value: -20, color: '#aa00aa' },
                { value: -18, color: '#801080' },
                { value: -16, color: '#600040' },
                { value: -14, color: '#303366' },
                { value: -12, color: '#003399' },
                { value: -10, color: '#0000cc' },
                { value: -8, color: '#0000ff' },
                { value: -6, color: '#0055ff' },
                { value: -4, color: '#0099ff' },
                { value: -2, color: '#33ccff' },
                { value: 0, color: '#66ffff' },
                { value: 2, color: '#66ff99' },
                { value: 4, color: '#66ff66' },
                { value: 6, color: '#66ff00' },
                { value: 8, color: '#bffa0e' },
                { value: 10, color: '#ffff09' },
                { value: 12, color: '#ffff86' },
                { value: 14, color: '#fde851' },
                { value: 16, color: '#ffcc00' },
                { value: 18, color: '#ff9900' },
                { value: 20, color: '#ff6900' },
                { value: 22, color: '#ff4d33' },
                { value: 24, color: '#ff3000' },
                { value: 26, color: '#ff0000' },
                { value: 28, color: '#e50000' },
                { value: 30, color: '#b20000' },
                { value: 32, color: '#990000' },
                { value: 34, color: '#6c0000' },
                { value: 36, color: '#800050' },
                { value: 38, color: '#a00077' },
                { value: 40, color: '#cc00cc' },
                { value: 42, color: '#ff00ff' },
                { value: 44, color: '#ff40ff' },
                { value: 46, color: '#ff80ff' },
            ]
        },
        temperature_ressentie: {
            label: 'Température ressentie', unit: '°C', decimals: 0, transparent_below: null,
            stops: [
                { value: -24, color: '#400040' },
                { value: -22, color: '#600060' },
                { value: -20, color: '#aa00aa' },
                { value: -18, color: '#801080' },
                { value: -16, color: '#600040' },
                { value: -14, color: '#303366' },
                { value: -12, color: '#003399' },
                { value: -10, color: '#0000cc' },
                { value: -8, color: '#0000ff' },
                { value: -6, color: '#0055ff' },
                { value: -4, color: '#0099ff' },
                { value: -2, color: '#33ccff' },
                { value: 0, color: '#66ffff' },
                { value: 2, color: '#66ff99' },
                { value: 4, color: '#66ff66' },
                { value: 6, color: '#66ff00' },
                { value: 8, color: '#bffa0e' },
                { value: 10, color: '#ffff09' },
                { value: 12, color: '#ffff86' },
                { value: 14, color: '#fde851' },
                { value: 16, color: '#ffcc00' },
                { value: 18, color: '#ff9900' },
                { value: 20, color: '#ff6900' },
                { value: 22, color: '#ff4d33' },
                { value: 24, color: '#ff3000' },
                { value: 26, color: '#ff0000' },
                { value: 28, color: '#e50000' },
                { value: 30, color: '#b20000' },
                { value: 32, color: '#990000' },
                { value: 34, color: '#6c0000' },
                { value: 36, color: '#800050' },
                { value: 38, color: '#a00077' },
                { value: 40, color: '#cc00cc' },
                { value: 42, color: '#ff00ff' },
                { value: 44, color: '#ff40ff' },
                { value: 46, color: '#ff80ff' },
            ]
        },
        point_rosee: {
            label: 'Point de rosée à 2 m', unit: '°C', decimals: 0, transparent_below: null,
            stops: [
                { value: -24, color: '#000010' },
                { value: -22, color: '#000520' },
                { value: -20, color: '#001040' },
                { value: -18, color: '#003366' },
                { value: -16, color: '#003399' },
                { value: -14, color: '#0000cc' },
                { value: -12, color: '#0000ff' },
                { value: -10, color: '#0066ff' },
                { value: -8, color: '#0099ff' },
                { value: -6, color: '#33ccff' },
                { value: -4, color: '#66ffff' },
                { value: -2, color: '#66ff99' },
                { value: 0, color: '#66ff66' },
                { value: 2, color: '#66ff00' },
                { value: 4, color: '#bffa0e' },
                { value: 6, color: '#ffff09' },
                { value: 8, color: '#ffff86' },
                { value: 10, color: '#fde851' },
                { value: 12, color: '#ffcc00' },
                { value: 14, color: '#ff9900' },
                { value: 16, color: '#ff6900' },
                { value: 18, color: '#ff4d33' },
                { value: 20, color: '#ff3000' },
                { value: 22, color: '#ff0000' },
                { value: 24, color: '#cc0000' },
                { value: 26, color: '#990000' },
                { value: 28, color: '#6c0000' },
                { value: 30, color: '#4f0000' },
            ]
        },
        humidex: {
            label: 'Indice Humidex', unit: '', decimals: 0, transparent_below: null,
            stops: [
                { value: -10, color: '#400040' },
                { value: -8, color: '#600060' },
                { value: -6, color: '#aa00aa' },
                { value: -4, color: '#801080' },
                { value: -2, color: '#600040' },
                { value: 0, color: '#303366' },
                { value: 2, color: '#003399' },
                { value: 4, color: '#0000cc' },
                { value: 6, color: '#0000ff' },
                { value: 8, color: '#0055ff' },
                { value: 10, color: '#0099ff' },
                { value: 12, color: '#33ccff' },
                { value: 14, color: '#66ffff' },
                { value: 16, color: '#66ff99' },
                { value: 18, color: '#66ff66' },
                { value: 20, color: '#66ff00' },
                { value: 22, color: '#bffa0e' },
                { value: 24, color: '#ffff09' },
                { value: 26, color: '#ffff86' },
                { value: 28, color: '#fde851' },
                { value: 30, color: '#ffcc00' },
                { value: 32, color: '#ff9900' },
                { value: 34, color: '#ff6900' },
                { value: 36, color: '#ff4d33' },
                { value: 38, color: '#ff3000' },
                { value: 40, color: '#ff0000' },
                { value: 42, color: '#e50000' },
                { value: 44, color: '#b20000' },
                { value: 46, color: '#990000' },
                { value: 48, color: '#6c0000' },
                { value: 50, color: '#800050' },
                { value: 52, color: '#a00077' },
                { value: 54, color: '#cc00cc' },
                { value: 56, color: '#ff00ff' },
                { value: 58, color: '#ff40ff' },
                { value: 60, color: '#ff80ff' },
            ]
        },
        pluie_1h: {
            label: 'Pluie horaire', unit: 'mm/h', decimals: 1, transparent_below: 0,
            stops: [
                { value: 0, color: '#ffffff' },
                { value: 0.1, color: '#97e6ff' },
                { value: 0.2, color: '#33ccff' },
                { value: 0.5, color: '#0099ff' },
                { value: 1, color: '#00ff99' },
                { value: 2, color: '#33cc66' },
                { value: 3, color: '#66cc33' },
                { value: 4, color: '#66ff00' },
                { value: 5, color: '#a4f22f' },
                { value: 6, color: '#b7cf0e' },
                { value: 7, color: '#d6f017' },
                { value: 8, color: '#cc9900' },
                { value: 9, color: '#ff9900' },
                { value: 10, color: '#ff9966' },
                { value: 15, color: '#cc9999' },
                { value: 20, color: '#cc6633' },
                { value: 25, color: '#cc3333' },
                { value: 30, color: '#ff0d0d' },
                { value: 40, color: '#c60000' },
                { value: 50, color: '#800000' },
                { value: 60, color: '#800050' },
                { value: 70, color: '#a00077' },
                { value: 100, color: '#cc00cc' },
                { value: 200, color: '#ff00ff' },
            ]
        },
        pluie_cumul: {
            label: 'Précipitations cumulées', unit: 'mm', decimals: 0, transparent_below: 0,
            stops: [
                { value: 0, color: '#ffffff' },
                { value: 0.5, color: '#97e6ff' },
                { value: 1, color: '#33ccff' },
                { value: 2, color: '#0099ff' },
                { value: 5, color: '#00ff99' },
                { value: 10, color: '#33cc66' },
                { value: 20, color: '#66cc33' },
                { value: 30, color: '#66ff00' },
                { value: 40, color: '#a4f22f' },
                { value: 50, color: '#b7cf0e' },
                { value: 60, color: '#d6f017' },
                { value: 70, color: '#cc9900' },
                { value: 80, color: '#ff9900' },
                { value: 90, color: '#ff9966' },
                { value: 100, color: '#cc9999' },
                { value: 150, color: '#cc6633' },
                { value: 200, color: '#cc3333' },
                { value: 300, color: '#ff0d0d' },
                { value: 400, color: '#c60000' },
                { value: 500, color: '#800000' },
                { value: 600, color: '#800050' },
                { value: 700, color: '#a00077' },
                { value: 800, color: '#cc00cc' },
            ]
        },
        reflectivite: {
            label: 'Réflectivité radar Doppler', unit: 'dBZ', decimals: 0, transparent_below: 0,
            stops: [
                { value: 5, color: '#64c8ff' },
                { value: 15, color: '#0000ff' },
                { value: 25, color: '#00ff00' },
                { value: 35, color: '#ffff00' },
                { value: 45, color: '#ffa500' },
                { value: 55, color: '#ff0000' },
                { value: 65, color: '#a000a0' },
            ]
        },
        graupel: {
            label: 'Graupel / Grésil', unit: 'mm', decimals: 1, transparent_below: 0,
            stops: [
                { value: 0.5, color: '#c8e6ff' },
                { value: 2, color: '#64c8ff' },
                { value: 5, color: '#ffa500' },
                { value: 15, color: '#c800c8' },
            ]
        },
        vent: {
            label: 'Vent moyen à 10 m', unit: 'km/h', decimals: 0, transparent_below: 0,
            stops: [
                { value: 0, color: '#ffffff' },
                { value: 5, color: '#97e6ff' },
                { value: 10, color: '#33ccff' },
                { value: 15, color: '#0099ff' },
                { value: 20, color: '#00ff99' },
                { value: 25, color: '#33cc66' },
                { value: 30, color: '#66cc33' },
                { value: 35, color: '#66ff00' },
                { value: 40, color: '#a4f22f' },
                { value: 45, color: '#b7cf0e' },
                { value: 50, color: '#d6f017' },
                { value: 55, color: '#cc9900' },
                { value: 60, color: '#ff9900' },
                { value: 65, color: '#ff9966' },
                { value: 70, color: '#cc9999' },
                { value: 75, color: '#cc6633' },
                { value: 80, color: '#cc3333' },
                { value: 85, color: '#ff0d0d' },
                { value: 90, color: '#c60000' },
                { value: 95, color: '#800000' },
                { value: 100, color: '#800050' },
                { value: 105, color: '#a00077' },
                { value: 110, color: '#cc00cc' },
                { value: 115, color: '#ff00ff' },
                { value: 120, color: '#ff40ff' },
                { value: 125, color: '#ff80ff' },
                { value: 130, color: '#ffa0ff' },
                { value: 140, color: '#ffffff' },
                { value: 150, color: '#e3e3e3' },
                { value: 160, color: '#c6c6c6' },
                { value: 170, color: '#aaaaaa' },
                { value: 180, color: '#8e8e8e' },
            ]
        },
        rafales: {
            label: 'Rafales maximales', unit: 'km/h', decimals: 0, transparent_below: 0,
            stops: [
                { value: 0, color: '#ffffff' },
                { value: 5, color: '#97e6ff' },
                { value: 10, color: '#33ccff' },
                { value: 15, color: '#0099ff' },
                { value: 20, color: '#00ff99' },
                { value: 25, color: '#33cc66' },
                { value: 30, color: '#66cc33' },
                { value: 35, color: '#66ff00' },
                { value: 40, color: '#a4f22f' },
                { value: 45, color: '#b7cf0e' },
                { value: 50, color: '#d6f017' },
                { value: 55, color: '#cc9900' },
                { value: 60, color: '#ff9900' },
                { value: 65, color: '#ff9966' },
                { value: 70, color: '#cc9999' },
                { value: 75, color: '#cc6633' },
                { value: 80, color: '#cc3333' },
                { value: 85, color: '#ff0d0d' },
                { value: 90, color: '#c60000' },
                { value: 100, color: '#800000' },
                { value: 110, color: '#800050' },
                { value: 120, color: '#a00077' },
                { value: 130, color: '#cc00cc' },
                { value: 140, color: '#ff00ff' },
                { value: 150, color: '#ff40ff' },
                { value: 160, color: '#ff80ff' },
                { value: 180, color: '#ffa0ff' },
                { value: 200, color: '#ffffff' },
                { value: 220, color: '#e3e3e3' },
                { value: 240, color: '#c6c6c6' },
            ]
        },
        rafales_cumul: {
            label: 'Rafales maximales cumulées', unit: 'km/h', decimals: 0, transparent_below: 0,
            stops: [
                { value: 0, color: '#ffffff' },
                { value: 5, color: '#97e6ff' },
                { value: 10, color: '#33ccff' },
                { value: 15, color: '#0099ff' },
                { value: 20, color: '#00ff99' },
                { value: 25, color: '#33cc66' },
                { value: 30, color: '#66cc33' },
                { value: 35, color: '#66ff00' },
                { value: 40, color: '#a4f22f' },
                { value: 45, color: '#b7cf0e' },
                { value: 50, color: '#d6f017' },
                { value: 55, color: '#cc9900' },
                { value: 60, color: '#ff9900' },
                { value: 65, color: '#ff9966' },
                { value: 70, color: '#cc9999' },
                { value: 75, color: '#cc6633' },
                { value: 80, color: '#cc3333' },
                { value: 85, color: '#ff0d0d' },
                { value: 90, color: '#c60000' },
                { value: 100, color: '#800000' },
                { value: 110, color: '#800050' },
                { value: 120, color: '#a00077' },
                { value: 130, color: '#cc00cc' },
                { value: 140, color: '#ff00ff' },
                { value: 150, color: '#ff40ff' },
                { value: 160, color: '#ff80ff' },
                { value: 180, color: '#ffa0ff' },
                { value: 200, color: '#ffffff' },
                { value: 220, color: '#e3e3e3' },
                { value: 240, color: '#c6c6c6' },
            ]
        },
        nebulosite: {
            label: 'Nébulosité totale', unit: '%', decimals: 0, transparent_below: 0,
            stops: [
                { value: 0, color: '#000000' },
                { value: 30, color: '#666666' },
                { value: 60, color: '#888888' },
                { value: 90, color: '#aaaaaa' },
                { value: 95, color: '#cccccc' },
                { value: 99, color: '#ffffff' },
            ]
        },
        nuages_bas: {
            label: 'Couverture nuages bas', unit: '%', decimals: 0, transparent_below: 0,
            stops: [
                { value: 0, color: '#000000' },
                { value: 30, color: '#666666' },
                { value: 60, color: '#888888' },
                { value: 90, color: '#aaaaaa' },
                { value: 95, color: '#cccccc' },
                { value: 99, color: '#ffffff' },
            ]
        },
        nuages_moyens: {
            label: 'Couverture nuages moyens', unit: '%', decimals: 0, transparent_below: 0,
            stops: [
                { value: 0, color: '#000000' },
                { value: 30, color: '#666666' },
                { value: 60, color: '#888888' },
                { value: 90, color: '#aaaaaa' },
                { value: 95, color: '#cccccc' },
                { value: 99, color: '#ffffff' },
            ]
        },
        nuages_eleves: {
            label: 'Couverture nuages élevés', unit: '%', decimals: 0, transparent_below: 0,
            stops: [
                { value: 0, color: '#000000' },
                { value: 30, color: '#666666' },
                { value: 60, color: '#888888' },
                { value: 90, color: '#aaaaaa' },
                { value: 95, color: '#cccccc' },
                { value: 99, color: '#ffffff' },
            ]
        },
        humidite: {
            label: 'Humidité relative à 2 m', unit: '%', decimals: 0, transparent_below: null,
            stops: [
                { value: 0, color: '#000000' },
                { value: 5, color: '#0c0c0c' },
                { value: 10, color: '#191919' },
                { value: 15, color: '#262626' },
                { value: 20, color: '#333333' },
                { value: 25, color: '#3f3f3f' },
                { value: 30, color: '#4c4c4c' },
                { value: 35, color: '#595959' },
                { value: 40, color: '#666666' },
                { value: 45, color: '#727272' },
                { value: 50, color: '#7f7f7f' },
                { value: 55, color: '#8c8c8c' },
                { value: 60, color: '#999999' },
                { value: 65, color: '#a5a5a5' },
                { value: 70, color: '#b2b2b2' },
                { value: 75, color: '#bfbfbf' },
                { value: 80, color: '#cccccc' },
                { value: 85, color: '#d8d8d8' },
                { value: 90, color: '#e5e5e5' },
                { value: 95, color: '#f2f2f2' },
                { value: 100, color: '#ffffff' },
            ]
        },
        mucape: {
            label: 'Instabilité convective (MUCAPE)', unit: 'J/kg', decimals: 0, transparent_below: 0,
            stops: [
                { value: 0, color: '#003366' },
                { value: 100, color: '#003399' },
                { value: 200, color: '#0000cc' },
                { value: 300, color: '#0000ff' },
                { value: 400, color: '#0066ff' },
                { value: 500, color: '#0099ff' },
                { value: 600, color: '#33ccff' },
                { value: 700, color: '#66ffff' },
                { value: 800, color: '#66ff99' },
                { value: 900, color: '#66ff66' },
                { value: 1000, color: '#66ff00' },
                { value: 1100, color: '#bffa0e' },
                { value: 1200, color: '#ffff09' },
                { value: 1300, color: '#ffff86' },
                { value: 1400, color: '#fde851' },
                { value: 1500, color: '#ffcc00' },
                { value: 1600, color: '#ff9900' },
                { value: 1700, color: '#ff6600' },
                { value: 1800, color: '#ff3333' },
                { value: 1900, color: '#ff3300' },
                { value: 2000, color: '#ff0000' },
                { value: 2100, color: '#e50000' },
                { value: 2200, color: '#b20000' },
                { value: 2300, color: '#b2003b' },
                { value: 2400, color: '#b20077' },
                { value: 2600, color: '#b200b2' },
                { value: 2800, color: '#cc00cc' },
                { value: 3000, color: '#e500e5' },
                { value: 3200, color: '#ff00ff' },
                { value: 3400, color: '#ff5fff' },
                { value: 3600, color: '#ffbfff' },
                { value: 4000, color: '#ffffff' },
                { value: 4500, color: '#aaaaaa' },
                { value: 5000, color: '#808080' },
                { value: 6000, color: '#404040' },
                { value: 7000, color: '#000000' },
            ]
        },
        neige: {
            label: 'Chutes de neige', unit: 'cm/h', decimals: 1, transparent_below: 0,
            stops: [
                { value: 0, color: '#ffffff' },
                { value: 0.1, color: '#97e6ff' },
                { value: 0.2, color: '#33ccff' },
                { value: 0.5, color: '#0099ff' },
                { value: 1, color: '#00ff99' },
                { value: 2, color: '#33cc66' },
                { value: 3, color: '#66cc33' },
                { value: 4, color: '#66ff00' },
                { value: 5, color: '#a4f22f' },
                { value: 6, color: '#b7cf0e' },
                { value: 7, color: '#d6f017' },
                { value: 8, color: '#cc9900' },
                { value: 9, color: '#ff9900' },
                { value: 10, color: '#ff9966' },
                { value: 15, color: '#cc9999' },
                { value: 20, color: '#cc6633' },
                { value: 25, color: '#cc3333' },
                { value: 30, color: '#ff0d0d' },
                { value: 40, color: '#c60000' },
                { value: 50, color: '#800000' },
                { value: 60, color: '#800050' },
                { value: 70, color: '#a00077' },
                { value: 80, color: '#cc00cc' },
                { value: 90, color: '#ff00ff' },
                { value: 100, color: '#ff40ff' },
                { value: 120, color: '#ff80ff' },
                { value: 140, color: '#ffa0ff' },
                { value: 160, color: '#c0c0c0' },
                { value: 180, color: '#909090' },
                { value: 200, color: '#606060' },
                { value: 250, color: '#303030' },
            ]
        },
        neige_au_sol: {
            label: 'Épaisseur neige au sol', unit: 'cm', decimals: 0, transparent_below: 0,
            stops: [
                { value: 0, color: '#ffffff' },
                { value: 0.1, color: '#97e6ff' },
                { value: 0.2, color: '#33ccff' },
                { value: 0.5, color: '#0099ff' },
                { value: 1, color: '#00ff99' },
                { value: 2, color: '#33cc66' },
                { value: 3, color: '#66cc33' },
                { value: 4, color: '#66ff00' },
                { value: 5, color: '#a4f22f' },
                { value: 6, color: '#b7cf0e' },
                { value: 7, color: '#d6f017' },
                { value: 8, color: '#cc9900' },
                { value: 9, color: '#ff9900' },
                { value: 10, color: '#ff9966' },
                { value: 15, color: '#cc9999' },
                { value: 20, color: '#cc6633' },
                { value: 25, color: '#cc3333' },
                { value: 30, color: '#ff0d0d' },
                { value: 40, color: '#c60000' },
                { value: 50, color: '#800000' },
                { value: 60, color: '#800050' },
                { value: 70, color: '#a00077' },
                { value: 80, color: '#cc00cc' },
                { value: 90, color: '#ff00ff' },
                { value: 100, color: '#ff40ff' },
                { value: 120, color: '#ff80ff' },
                { value: 140, color: '#ffa0ff' },
                { value: 160, color: '#c0c0c0' },
                { value: 180, color: '#909090' },
                { value: 200, color: '#606060' },
                { value: 250, color: '#303030' },
            ]
        },
        equivalent_eau_neige: {
            label: 'Cumul neigeux équivalent eau', unit: 'mm', decimals: 1, transparent_below: 0,
            stops: [
                { value: 1, color: '#c8e6ff' },
                { value: 5, color: '#64b4ff' },
                { value: 15, color: '#3264c8' },
                { value: 30, color: '#0000b4' },
            ]
        },
        pression: {
            label: 'Pression niveau mer', unit: 'hPa', decimals: 0, transparent_below: null,
            stops: [
                { value: 960, color: '#820082' },
                { value: 975, color: '#0000c8' },
                { value: 985, color: '#0096ff' },
                { value: 995, color: '#00c896' },
                { value: 1005, color: '#00b400' },
                { value: 1013, color: '#c8c8c8' },
                { value: 1020, color: '#ffdc64' },
                { value: 1030, color: '#ff9600' },
                { value: 1040, color: '#c85000' },
            ]
        },
        vagues: {
            label: 'Hauteur des vagues / Houle', unit: 'm', decimals: 1, transparent_below: null,
            stops: [
                { value: 0, color: '#ffffff' },
                { value: 0.5, color: '#97e6ff' },
                { value: 1.0, color: '#33ccff' },
                { value: 1.5, color: '#0099ff' },
                { value: 2.0, color: '#00ff99' },
                { value: 2.5, color: '#33cc66' },
                { value: 3.0, color: '#66cc33' },
                { value: 3.5, color: '#66ff00' },
                { value: 4.0, color: '#a4f22f' },
                { value: 4.5, color: '#b7cf0e' },
                { value: 5.0, color: '#d6f017' },
                { value: 5.5, color: '#cc9900' },
                { value: 6.0, color: '#ff9900' },
                { value: 6.5, color: '#ff9966' },
                { value: 7.0, color: '#cc9999' },
                { value: 7.5, color: '#cc6633' },
                { value: 8.0, color: '#cc3333' },
                { value: 8.5, color: '#ff0d0d' },
                { value: 9.0, color: '#c60000' },
                { value: 9.5, color: '#800000' },
                { value: 10.0, color: '#800050' },
                { value: 11.0, color: '#a00077' },
                { value: 12.0, color: '#cc00cc' },
                { value: 13.0, color: '#ff00ff' },
                { value: 14.0, color: '#ff40ff' },
                { value: 15.0, color: '#ff80ff' },
                { value: 16.0, color: '#ffa0ff' },
                { value: 17.0, color: '#ffffff' },
            ]
        },
        houle: {
            label: 'Hauteur significative de la houle', unit: 'm', decimals: 1, transparent_below: null,
            stops: [
                { value: 0, color: '#ffffff' },
                { value: 0.5, color: '#97e6ff' },
                { value: 1.0, color: '#33ccff' },
                { value: 1.5, color: '#0099ff' },
                { value: 2.0, color: '#00ff99' },
                { value: 2.5, color: '#33cc66' },
                { value: 3.0, color: '#66cc33' },
                { value: 3.5, color: '#66ff00' },
                { value: 4.0, color: '#a4f22f' },
                { value: 4.5, color: '#b7cf0e' },
                { value: 5.0, color: '#d6f017' },
                { value: 5.5, color: '#cc9900' },
                { value: 6.0, color: '#ff9900' },
                { value: 6.5, color: '#ff9966' },
                { value: 7.0, color: '#cc9999' },
                { value: 7.5, color: '#cc6633' },
                { value: 8.0, color: '#cc3333' },
                { value: 8.5, color: '#ff0d0d' },
                { value: 9.0, color: '#c60000' },
                { value: 9.5, color: '#800000' },
                { value: 10.0, color: '#800050' },
                { value: 11.0, color: '#a00077' },
                { value: 12.0, color: '#cc00cc' },
                { value: 13.0, color: '#ff00ff' },
                { value: 14.0, color: '#ff40ff' },
                { value: 15.0, color: '#ff80ff' },
                { value: 16.0, color: '#ffa0ff' },
                { value: 17.0, color: '#ffffff' },
            ]
        },
        periode_vagues: {
            label: 'Période des vagues / Houle', unit: 's', decimals: 1, transparent_below: null,
            stops: [
                { value: 0, color: '#ffffff' },
                { value: 2.0, color: '#1e3c6e' },
                { value: 4.0, color: '#2878b9' },
                { value: 6.0, color: '#32b4e1' },
                { value: 8.0, color: '#3cd7b4' },
                { value: 10.0, color: '#5ad750' },
                { value: 12.0, color: '#b9e128' },
                { value: 14.0, color: '#f5cd14' },
                { value: 16.0, color: '#ff8c00' },
                { value: 18.0, color: '#f0321e' },
                { value: 20.0, color: '#be0050' },
                { value: 22.0, color: '#f000dc' },
                { value: 25.0, color: '#ffffff' },
            ]
        },
        periode: {
            label: 'Période des vagues / Houle', unit: 's', decimals: 1, transparent_below: null,
            stops: [
                { value: 0, color: '#ffffff' },
                { value: 2.0, color: '#1e3c6e' },
                { value: 4.0, color: '#2878b9' },
                { value: 6.0, color: '#32b4e1' },
                { value: 8.0, color: '#3cd7b4' },
                { value: 10.0, color: '#5ad750' },
                { value: 12.0, color: '#b9e128' },
                { value: 14.0, color: '#f5cd14' },
                { value: 16.0, color: '#ff8c00' },
                { value: 18.0, color: '#f0321e' },
                { value: 20.0, color: '#be0050' },
                { value: 22.0, color: '#f000dc' },
                { value: 25.0, color: '#ffffff' },
            ]
        },
        pression_surface: {
            label: 'Pression au sol', unit: 'hPa', decimals: 0, transparent_below: null,
            stops: [
                { value: 800, color: '#820082' },
                { value: 900, color: '#0000c8' },
                { value: 960, color: '#00b400' },
                { value: 1013, color: '#c8c8c8' },
                { value: 1040, color: '#c85000' },
            ]
        },
        geopotentiel_500: {
            label: 'Géop. Z500 & pression au sol', unit: 'dam', decimals: 0, transparent_below: null,
            stops: [
                { value: 492, color: '#400040' },
                { value: 496, color: '#600060' },
                { value: 500, color: '#aa00aa' },
                { value: 504, color: '#801080' },
                { value: 508, color: '#600040' },
                { value: 512, color: '#303366' },
                { value: 516, color: '#003399' },
                { value: 520, color: '#0000cc' },
                { value: 524, color: '#0000ff' },
                { value: 528, color: '#0055ff' },
                { value: 532, color: '#0099ff' },
                { value: 536, color: '#33ccff' },
                { value: 540, color: '#66ffff' },
                { value: 544, color: '#66ff99' },
                { value: 548, color: '#66ff66' },
                { value: 552, color: '#66ff00' },
                { value: 556, color: '#bffa0e' },
                { value: 560, color: '#ffff09' },
                { value: 564, color: '#ffff86' },
                { value: 568, color: '#fde851' },
                { value: 572, color: '#ffcc00' },
                { value: 576, color: '#ff9900' },
                { value: 580, color: '#ff6900' },
                { value: 584, color: '#ff4d33' },
                { value: 588, color: '#ff3000' },
                { value: 592, color: '#ff0000' },
                { value: 596, color: '#cc0000' },
                { value: 600, color: '#990000' },
                { value: 604, color: '#6c0000' },
                { value: 608, color: '#4f0000' },
                { value: 612, color: '#4f0000' },
            ]
        },
        probabilite: {
            label: 'Probabilité de dépassement', unit: '%', decimals: 0, transparent_below: 5,
            stops: [
                { value: 0, color: 'rgba(0,0,0,0)' },
                { value: 10, color: '#40b4ff' },
                { value: 25, color: '#28d296' },
                { value: 40, color: '#b4f028' },
                { value: 50, color: '#ffe600' },
                { value: 65, color: '#ffa000' },
                { value: 80, color: '#f01414' },
                { value: 95, color: '#be0082' },
                { value: 100, color: '#8c00c8' }
            ]
        },
    };
    PALETTES.temperature_850 = {
        label: 'Température à 850 hPa (~1 500 m)', unit: '°C', decimals: 1, transparent_below: null,
        stops: PALETTES.temperature.stops
    };
    PALETTES.temperature_min_24h = {
        label: 'Température minimale Tn (24h)', unit: '°C', decimals: 1, transparent_below: null,
        stops: PALETTES.temperature.stops
    };
    PALETTES.temperature_max_24h = {
        label: 'Température maximale Tx (24h)', unit: '°C', decimals: 1, transparent_below: null,
        stops: PALETTES.temperature.stops
    };
    PALETTES.pluie_24h = {
        label: 'Précipitations sur 24h', unit: 'mm', decimals: 0, transparent_below: 0,
        stops: PALETTES.pluie_cumul.stops
    };
    PALETTES.rafales_max_24h = {
        label: 'Rafales maximales (24h)', unit: 'km/h', decimals: 0, transparent_below: 0,
        stops: PALETTES.rafales.stops
    };
    PALETTES.mucape_max_24h = {
        label: 'Instabilité maximale (24h)', unit: 'J/kg', decimals: 0, transparent_below: 0,
        stops: PALETTES.mucape.stops
    };
    PALETTES.neige_24h = {
        label: 'Épaisseur maximale de neige (24h)', unit: 'cm', decimals: 0, transparent_below: 0,
        stops: PALETTES.neige_au_sol.stops
    };
    PALETTES.geopotentiel_500_meteociel = PALETTES.geopotentiel_500;

    // Calques de Probabilités 24h
    var probLayerLabels = {
        prob_tmax_25: 'Probabilité Tmax ≥ 25 °C (24h)',
        prob_tmax_30: 'Probabilité Tmax ≥ 30 °C (24h)',
        prob_tmax_35: 'Probabilité Tmax ≥ 35 °C (24h)',
        prob_tmax_40: 'Probabilité Tmax ≥ 40 °C (24h)',
        prob_tmin_0: 'Probabilité Gelée Tmin ≤ 0 °C (24h)',
        prob_tmin_m5: 'Probabilité Forte Gelée ≤ -5 °C',
        prob_vent_60: 'Probabilité Rafales ≥ 60 km/h (24h)',
        prob_vent_80: 'Probabilité Rafales ≥ 80 km/h (24h)',
        prob_vent_100: 'Probabilité Rafales ≥ 100 km/h (24h)',
        prob_vent_120: 'Probabilité Rafales ≥ 120 km/h (24h)',
        prob_pluie_10: 'Probabilité Pluie 24h ≥ 10 mm',
        prob_pluie_25: 'Probabilité Pluie 24h ≥ 25 mm',
        prob_pluie_50: 'Probabilité Pluie 24h ≥ 50 mm',
        prob_pluie_70: 'Probabilité Pluie 24h ≥ 70 mm',
        prob_neige_1: 'Probabilité Neige 24h ≥ 1 cm',
        prob_neige_5: 'Probabilité Neige 24h ≥ 5 cm',
        prob_mucape_500: 'Probabilité Risque Orageux (24h)',
        prob_mucape_1500: 'Probabilité Orages Violents (24h)'
    };
    Object.keys(probLayerLabels).forEach(function (pk) {
        PALETTES[pk] = {
            label: probLayerLabels[pk],
            unit: '%',
            decimals: 0,
            transparent_below: 5,
            stops: PALETTES.probabilite.stops
        };
    });

    function getLayerPalette(key) { return PALETTES[key] || PALETTES.temperature; }
    function paletteGradientCSS(key) {
        var pal = getLayerPalette(key); var stops = pal.stops;
        var low = (pal.transparent_below !== null && pal.transparent_below !== undefined) ? pal.transparent_below : stops[0].value;
        var max = stops[stops.length - 1].value; var span = (max - low) || 1; var items = [];
        if (pal.transparent_below !== null && pal.transparent_below !== undefined) items.push('rgba(0,0,0,0) 0%');
        stops.forEach(function (s) { items.push(s.color + ' ' + (((s.value - low) / span * 100).toFixed(1)) + '%'); });
        return 'linear-gradient(to right, ' + items.join(', ') + ')';
    }
    function paletteTicks(key) {
        var pal = getLayerPalette(key); var stops = pal.stops;
        var low = (pal.transparent_below !== null && pal.transparent_below !== undefined) ? pal.transparent_below : stops[0].value;
        var max = stops[stops.length - 1].value;
        // Z500 : toutes les bornes de classes (492, 496, ... 612) — style Météociel
        if (key === 'geopotentiel_500' || key === 'geopotentiel_500_meteociel') {
            var zticks = [];
            for (var zi = 0; zi < stops.length; zi += 1) zticks.push(stops[zi].value);
            return zticks;
        }
        if (key === 'vagues' || key === 'houle') {
            return [0, 1, 2, 3, 4, 5, 6, 8, 10, 12, 14, 16];
        }
        if (key === 'periode_vagues' || key === 'periode') {
            return [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22];
        }
        var ticks = [];
        for (var i = 0; i < 5; i += 1) ticks.push(formatTickValue(low + (max - low) * i / 4));
        return ticks;
    }
    function formatTickValue(v) {
        var rounded = Math.abs(v) >= 100 ? Math.round(v) : Math.round(v * 10) / 10;
        return String(rounded);
    }
    window.WEATHER_PALETTES = PALETTES; window.getLayerPalette = getLayerPalette;
    window.paletteGradientCSS = paletteGradientCSS; window.paletteTicks = paletteTicks;
})();
